// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBf31w7o2fm80ajk7KkxxXdKJyZLeDrQ',
    appId: '1:964353779137:web:ad8e817f19d6d80c6a7b40',
    messagingSenderId: '964353779137',
    projectId: 'task-manager-f3f58',
    authDomain: 'task-manager-f3f58.firebaseapp.com',
    storageBucket: 'task-manager-f3f58.firebasestorage.app',
    measurementId: 'G-WSVVMBLC91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2891wLksSkG_uzPBMsWkS0PcwpJDw-g',
    appId: '1:964353779137:android:4cb23734734a24cc6a7b40',
    messagingSenderId: '964353779137',
    projectId: 'task-manager-f3f58',
    storageBucket: 'task-manager-f3f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrk7KIk-Ep4r0eTlr2d0xA9r3ErxZ2zw',
    appId: '1:964353779137:ios:852786bd0d5332886a7b40',
    messagingSenderId: '964353779137',
    projectId: 'task-manager-f3f58',
    storageBucket: 'task-manager-f3f58.firebasestorage.app',
    iosBundleId: 'com.example.gigWorkerTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnrk7KIk-Ep4r0eTlr2d0xA9r3ErxZ2zw',
    appId: '1:964353779137:ios:852786bd0d5332886a7b40',
    messagingSenderId: '964353779137',
    projectId: 'task-manager-f3f58',
    storageBucket: 'task-manager-f3f58.firebasestorage.app',
    iosBundleId: 'com.example.gigWorkerTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrBf31w7o2fm80ajk7KkxxXdKJyZLeDrQ',
    appId: '1:964353779137:web:25d6f92c247d53a26a7b40',
    messagingSenderId: '964353779137',
    projectId: 'task-manager-f3f58',
    authDomain: 'task-manager-f3f58.firebaseapp.com',
    storageBucket: 'task-manager-f3f58.firebasestorage.app',
    measurementId: 'G-Y3X3KK3BTW',
  );
}
