name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5 
          channel: stable

      - name: Install Dependencies
        run: flutter pub get



      - name: Clean Flutter Build
        run: flutter clean

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Web Release
        run: flutter build web

      - name: Upload APK to GitHub Releases
        env:
          personal_token: ${{ secrets.TOKEN }}
        run: |
          LATEST_TAG=$(date +'%Y.%m.%d-%H%M%S')
          gh release create "$LATEST_TAG" --title "Release $LATEST_TAG" --notes "Latest APK release" --prerelease || echo "Release already exists"
          gh release upload "$LATEST_TAG" build/app/outputs/flutter-apk/app-release.apk --clobber

      - name: Ensure gh-pages branch exists
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git commit --allow-empty -m "Initialize gh-pages branch" || echo "Branch already exists"
          git push origin gh-pages || echo "Branch already exists"

      - name: Deploy Web to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
